#!/usr/bin/env bash
# Emit the Civitai Sensei cover as flat vector SVG.
#
# Composition — "Ask. It reads the catalog."
#   LEFT/CENTRE  a staggered lattice of small diamonds: the catalog, laid out as an even
#                corpus rather than a funnel. (A funnel silhouette is Custom Generators'
#                mark; reusing it here would blur two apps in the same store row.)
#   FOCUS        the lattice does not thin toward the seal, it LIGHTENS — each column is
#                interpolated one step further from matcha toward the pale tint. The focus
#                is therefore a colour gradient, not a density gradient, which keeps the
#                corpus reading as complete (the assistant read all of it) while still
#                aiming the eye rightward.
#                🔴 Per COLUMN, never per DIAMOND. The first cut thresholded on each
#                diamond's radial distance to the seal, which produced a jagged tint/matcha
#                boundary mid-lattice — it read as a rendering fault rather than a decision.
#                A columnar ramp is monotonic left-to-right and unmistakably intentional.
#   RIGHT        the seal: the icon mark at 0.6 scale, exactly. Same frame/stroke/core
#                proportions, so the cover and the icon are provably the same mark.
#
# Deterministic: no randomness anywhere, so the output is byte-reproducible.
set -euo pipefail
OUT="${1:?usage: gen-cover.sh <out.svg>}"

W=1600; H=900
INK="#0B0E14"; MATCHA="#7CB342"; TINT="#C8E6A0"; CINNABAR="#E8503A"

# seal = icon mark (frame 345 / stroke 84 / core 140) scaled by 0.6
SEAL_X=1235; SEAL_Y=450
FRAME=207; STROKE=50; CORE=84

# lattice
COL0=130; COLSTEP=88; NCOL=9
ROWSTEP=118

{
  printf '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" width="%d" height="%d" role="img" aria-label="Civitai Sensei cover">\n' "$W" "$H" "$W" "$H"
  cat <<HDR
  <!-- Civitai Sensei cover — "Ask. It reads the catalog."
       Generated by gen-cover.sh — deterministic, no randomness, byte-reproducible.
       The corpus lattice stays at full density and LIGHTENS toward the seal, so the
       focus is carried by colour rather than by a taper (a taper is Custom Generators').
       The seal is the icon mark at exactly 0.6 scale: frame 345->207, stroke 84->50,
       core 140->84, so the two assets are the same mark by construction.
       Palette: ink $INK ground - corpus $MATCHA - read $TINT - answer $CINNABAR. -->
HDR
  printf '  <rect width="%d" height="%d" fill="%s"/>\n' "$W" "$H" "$INK"

  # ---- the corpus -------------------------------------------------------------
  printf '  <!-- the corpus: 9 staggered columns, uniform density, brightening rightward -->\n'
  awk -v c0="$COL0" -v cs="$COLSTEP" -v nc="$NCOL" -v rs="$ROWSTEP" 'BEGIN{
    # endpoints of the ramp: MATCHA #7CB342 -> TINT #C8E6A0
    r0 = 124; g0 = 179; b0 = 66
    r1 = 200; g1 = 230; b1 = 160
    for (i = 0; i < nc; i++) {
      x = c0 + i * cs
      rad = 22 + i * 1.25                   # a touch larger as the eye travels right
      u = i / (nc - 1)                      # 0 at the far left, 1 at the column nearest the seal
      cr = r0 + u * (r1 - r0)
      cg = g0 + u * (g1 - g0)
      cb = b0 + u * (b1 - b0)
      f = sprintf("#%02X%02X%02X", int(cr + 0.5), int(cg + 0.5), int(cb + 0.5))
      # even columns carry 6 rows, odd columns 5, offset by half a row: a staggered lattice
      if (i % 2 == 0) { n = 6; y0 = 450 - 2.5 * rs } else { n = 5; y0 = 450 - 2 * rs }
      for (k = 0; k < n; k++) {
        y = y0 + k * rs
        printf "  <polygon fill=\"%s\" points=\"%.1f,%.1f %.1f,%.1f %.1f,%.1f %.1f,%.1f\"/>\n", \
               f, x, y - rad, x + rad, y, x, y + rad, x - rad, y
      }
    }
  }'

  # ---- the seal ---------------------------------------------------------------
  printf '  <!-- the seal: the icon mark at 0.6 scale -->\n'
  awk -v x="$SEAL_X" -v y="$SEAL_Y" -v fm="$FRAME" -v sw="$STROKE" -v co="$CORE" \
      -v t="$TINT" -v c="$CINNABAR" 'BEGIN{
    printf "  <polygon fill=\"none\" stroke=\"%s\" stroke-width=\"%d\" stroke-linejoin=\"round\"\n", t, sw
    printf "           points=\"%.0f,%.0f %.0f,%.0f %.0f,%.0f %.0f,%.0f\"/>\n", \
           x, y - fm, x + fm, y, x, y + fm, x - fm, y
    printf "  <polygon fill=\"%s\" points=\"%.0f,%.0f %.0f,%.0f %.0f,%.0f %.0f,%.0f\"/>\n", \
           c, x, y - co, x + co, y, x, y + co, x - co, y
  }'

  printf '</svg>\n'
} > "$OUT"
echo "wrote $OUT"
